#pragma once

#include "AppConfig.h"

#if M5EPUB_ENABLE_WEB_PORTAL
#include <pgmspace.h>

static const char kPortalPage[] PROGMEM = R"PORTAL(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>M5Paper Library</title><style>
:root{color-scheme:light dark;--bg:#f5f1e8;--paper:#fbf9f4;--ink:#211f1b;--muted:#6d6961;--line:#b8b1a6;--soft:#e8e2d8;--shadow:#211f1b14;--radius:14px}*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:16px Georgia,"Times New Roman",serif;min-height:100vh}main{max-width:920px;margin:auto;padding:36px 20px 64px}
.hero{text-align:center;margin-bottom:24px}.brand{width:58px;height:58px;margin:auto}.brand svg{width:100%;height:100%}h1{font-size:clamp(2rem,6vw,3rem);font-weight:500;margin:.35rem 0}.subtitle{color:var(--muted);margin:0;font-size:1rem}
.card{background:var(--paper);border:1px solid var(--line);border-radius:var(--radius);box-shadow:0 8px 28px var(--shadow)}.storage{display:grid;grid-template-columns:auto 1fr auto;gap:18px;align-items:center;padding:18px 22px;margin-bottom:18px}.storage .ico{width:34px;height:34px}.storage strong{font-size:1.12rem;font-weight:500}.storage-detail{font:13px ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--muted);white-space:nowrap}
.meter{height:7px;background:var(--soft);border:1px solid var(--line);border-radius:99px;overflow:hidden;margin-top:9px}.meter span{display:block;height:100%;background:var(--ink);width:0}
.toolbar{display:flex;align-items:center;justify-content:space-between;gap:14px;margin:14px 0}.actions{display:flex;gap:9px}.crumb{display:flex;align-items:center;gap:7px;min-width:0;overflow:auto;white-space:nowrap}.crumb a{color:inherit;text-decoration:none}.crumb a:hover{text-decoration:underline}
button{font:15px Georgia,"Times New Roman",serif;background:var(--paper);color:var(--ink);border:1px solid var(--line);border-radius:9px;padding:10px 15px;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:8px;min-height:42px}button:hover{background:var(--soft)}button:active{transform:translateY(1px)}button:focus-visible,input:focus-visible,a:focus-visible{outline:3px double var(--ink);outline-offset:3px}.ico{width:20px;height:20px;display:inline-block;vertical-align:middle;flex:none}.ico svg,button>svg{width:100%;height:100%;display:block}button>svg{width:20px;height:20px;flex:none}
.drop{border:1.5px dashed var(--muted);border-radius:var(--radius);background:var(--paper);min-height:164px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:24px;cursor:pointer;transition:border-color .15s,background .15s}.drop:hover,.drop.over{border-style:solid;background:var(--soft)}.drop .ico{width:46px;height:46px;margin-bottom:8px}.drop strong{font-size:1.25rem;font-weight:500}.drop small{font:13px ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--muted);margin-top:7px}
.section-title{font-size:1.35rem;font-weight:500;margin:22px 0 10px}.empty{padding:26px;text-align:center;color:var(--muted)}ul{list-style:none;margin:0;padding:0;overflow:hidden}.entry{display:grid;grid-template-columns:auto minmax(0,1fr) auto auto;gap:13px;align-items:center;padding:14px 16px;border-bottom:1px solid var(--line)}.entry:last-child{border-bottom:0}.entry-link{color:inherit;text-decoration:none;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:1.04rem}.entry-link:hover{text-decoration:underline}.meta{font:13px ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--muted)}.icon-button{width:40px;height:40px;padding:8px;background:transparent;border-color:transparent}.icon-button:hover{border-color:var(--line)}
.job{display:grid;grid-template-columns:auto minmax(0,1fr) minmax(120px,260px) auto;gap:13px;align-items:center;padding:14px 16px;margin-bottom:8px}.job-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.job progress{width:100%;height:9px;accent-color:var(--ink)}.job-state{font:13px ui-monospace,SFMono-Regular,Consolas,monospace}
.toast{position:fixed;right:24px;bottom:24px;max-width:min(390px,calc(100vw - 32px));background:var(--paper);border:1px solid var(--line);border-radius:12px;box-shadow:0 12px 36px #0003;padding:13px 17px;display:flex;align-items:center;gap:10px;transform:translateY(30px);opacity:0;pointer-events:none;transition:.2s;z-index:20}.toast.show{transform:none;opacity:1}.toast.error{border-style:double}
dialog{width:min(430px,calc(100vw - 30px));background:var(--paper);color:var(--ink);border:1px solid var(--line);border-radius:var(--radius);box-shadow:0 16px 50px #0005;padding:22px}dialog::backdrop{background:#211f1b88}.dialog-title{font-size:1.3rem;margin:0 0 8px}.dialog-text{color:var(--muted);margin:0 0 16px}.dialog-input{width:100%;font:16px Georgia,serif;padding:11px;border:1px solid var(--line);border-radius:8px;background:var(--bg);color:var(--ink);margin-bottom:16px}.dialog-actions{display:flex;justify-content:flex-end;gap:8px}
@media(max-width:620px){main{padding:24px 14px 48px}.storage{grid-template-columns:auto 1fr}.storage-detail{grid-column:1/-1}.toolbar{align-items:stretch;flex-direction:column}.actions button{flex:1}.entry{grid-template-columns:auto minmax(0,1fr) auto}.entry .meta{grid-column:2}.job{grid-template-columns:auto minmax(0,1fr) auto}.job progress{grid-column:2/-1}.toast{right:16px;bottom:16px}}
@media(prefers-color-scheme:dark){:root{--bg:#171613;--paper:#211f1b;--ink:#eee9df;--muted:#aaa398;--line:#5f5a52;--soft:#302d28;--shadow:#0005}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
</style></head><body><main>
<header class="hero"><div class="brand" id="brand"></div><h1 id="title">M5Paper Library</h1><p class="subtitle" id="subtitle"></p></header>
<section class="card storage"><span class="ico" id="storageIcon"></span><div><strong id="space"></strong><div class="meter"><span id="usedBar"></span></div></div><div class="storage-detail" id="storageDetail"></div></section>
<div class="toolbar"><nav class="crumb" id="crumb"></nav><div class="actions"><button id="mkdir"></button><button id="pick"></button><input id="files" type="file" accept=".epub,application/epub+zip" multiple hidden></div></div>
<div id="drop" class="drop" role="button" tabindex="0"><span class="ico" id="uploadIcon"></span><strong id="dropTitle"></strong><small id="dropHint"></small></div>
<h2 class="section-title" id="filesTitle"></h2><ul class="card" id="list"></ul><section id="jobsWrap" hidden><h2 class="section-title" id="jobsTitle"></h2><div id="jobs"></div></section>
</main><div class="toast" id="toast"><span class="ico" id="toastIcon"></span><span id="toastText"></span></div>
<dialog id="dialog"><h2 class="dialog-title" id="dialogTitle"></h2><p class="dialog-text" id="dialogText"></p><input class="dialog-input" id="dialogInput"><div class="dialog-actions"><button id="dialogCancel"></button><button id="dialogOk"></button></div></dialog>
<script>
const pt=document.cookie.split(';').some(x=>x.trim()==='m5epub_lang=pt');document.documentElement.lang=pt?'pt-BR':'en';
const t=pt?{title:'Biblioteca do M5Paper',subtitle:'Envie seus livros diretamente para o cartão microSD',folder:'Nova pasta',upload:'Enviar EPUB',drop:'Arraste arquivos EPUB aqui',dropHint:'ou selecione arquivos do seu dispositivo',available:'disponíveis',total:'Total',used:'Usado',empty:'Esta pasta está vazia',files:'Arquivos',jobs:'Envios',del:'Apagar',confirmTitle:'Apagar item',confirm:'Tem certeza de que deseja apagar',nameTitle:'Nova pasta',name:'Digite o nome da pasta',cancel:'Cancelar',create:'Criar',remove:'Apagar',failed:'Falha',success:'Livro enviado com sucesso',network:'Erro de rede'}:{title:'M5Paper Library',subtitle:'Send books directly to the microSD card',folder:'New folder',upload:'Upload EPUB',drop:'Drop EPUB files here',dropHint:'or select files from your device',available:'available',total:'Total',used:'Used',empty:'This folder is empty',files:'Files',jobs:'Uploads',del:'Delete',confirmTitle:'Delete item',confirm:'Are you sure you want to delete',nameTitle:'New folder',name:'Enter the folder name',cancel:'Cancel',create:'Create',remove:'Delete',failed:'Failed',success:'Book uploaded successfully',network:'Network error'};document.title=t.title;
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={book:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M3 5.5c3-1.5 6-1.2 9 .8 3-2 6-2.3 9-.8v14c-3-1.3-6-1-9 1-3-2-6-2.3-9-1z"/><path d="M12 6.3v14.2"/></svg>',storage:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M6 2h9l3 3v17H6z"/><path d="M9 2v5m3-5v5m3-5v5M9 15h6v4H9z"/></svg>',home:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m3 11 9-8 9 8v10h-6v-6H9v6H3z"/></svg>',folder:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M3 6h7l2 2h9v11H3z"/></svg>',file:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M6 2h8l4 4v16H6z"/><path d="M14 2v5h5"/></svg>',upload:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 16V3m-5 5 5-5 5 5M4 14v7h16v-7"/></svg>',newFolder:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M3 7h7l2 2h9v10H3z"/><path d="M15 12v5m-2.5-2.5h5"/></svg>',trash:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M4 7h16M9 3h6l1 4H8zM7 7l1 14h8l1-14M10 11v6m4-6v6"/></svg>',check:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/></svg>',error:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="9"/><path d="M12 7v6m0 4h.01"/></svg>'};
let path='/',toastTimer;$('#brand').innerHTML=icons.book;$('#storageIcon').innerHTML=icons.storage;$('#uploadIcon').innerHTML=icons.upload;$('#title').textContent=t.title;$('#subtitle').textContent=t.subtitle;$('#dropTitle').textContent=t.drop;$('#dropHint').textContent=t.dropHint;$('#filesTitle').textContent=t.files;$('#jobsTitle').textContent=t.jobs;$('#mkdir').innerHTML=icons.newFolder+'<span>'+t.folder+'</span>';$('#pick').innerHTML=icons.upload+'<span>'+t.upload+'</span>';
const natural=(a,b)=>a.name.localeCompare(b.name,pt?'pt-BR':'en',{numeric:true,sensitivity:'base'}),size=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KiB':n<1073741824?(n/1048576).toFixed(1)+' MiB':(n/1073741824).toFixed(1)+' GiB';
function toast(message,error=false){clearTimeout(toastTimer);$('#toastIcon').innerHTML=error?icons.error:icons.check;$('#toastText').textContent=message;$('#toast').className='toast show'+(error?' error':'');toastTimer=setTimeout(()=>$('#toast').className='toast',3200)}
function crumbs(){let parts=path.split('/').filter(Boolean),html='<span class="ico">'+icons.home+'</span><a href="#" data-p="/">/</a>',p='';for(const x of parts){p+='/'+x;html+=' <span>/</span> <a href="#" data-p="'+esc(p)+'">'+esc(x)+'</a>'}$('#crumb').innerHTML=html;$('#crumb').querySelectorAll('a').forEach(a=>a.onclick=e=>{e.preventDefault();path=a.dataset.p;load()})}
async function load(){crumbs();let r=await fetch('/api/list?path='+encodeURIComponent(path),{cache:'no-store'}),d=await r.json();if(!r.ok){toast(d.error,true);return}let free=d.freeKiB*1024,total=d.totalKiB*1024,used=Math.max(0,total-free);$('#space').textContent=size(free)+' '+t.available;$('#storageDetail').textContent=t.total+': '+size(total)+'  |  '+t.used+': '+size(used);$('#usedBar').style.width=(total?Math.min(100,used*100/total):0)+'%';let a=d.entries.sort((x,y)=>x.directory!==y.directory?x.directory?-1:1:natural(x,y));$('#list').innerHTML=a.length?a.map(x=>'<li class="entry"><span class="ico">'+(x.directory?icons.folder:icons.file)+'</span><a class="entry-link" href="#">'+esc(x.name)+'</a><span class="meta">'+(x.directory?'':size(x.size))+'</span><button class="icon-button" title="'+t.del+'" aria-label="'+t.del+' '+esc(x.name)+'">'+icons.trash+'</button></li>').join(''):'<li class="empty">'+t.empty+'</li>';[...$('#list').children].forEach((li,i)=>{if(!a[i])return;li.querySelector('.entry-link').onclick=e=>{e.preventDefault();if(a[i].directory){path=(path==='/'?'':path)+'/'+a[i].name;load()}};li.querySelector('button').onclick=()=>remove(a[i])})}
function modal({title,text,input=false,ok}){return new Promise(resolve=>{$('#dialogTitle').textContent=title;$('#dialogText').textContent=text;$('#dialogInput').hidden=!input;$('#dialogInput').value='';$('#dialogCancel').textContent=t.cancel;$('#dialogOk').textContent=ok;let done=value=>{$('#dialog').close();resolve(value)};$('#dialogCancel').onclick=()=>done(null);$('#dialogOk').onclick=()=>done(input?$('#dialogInput').value.trim():true);$('#dialog').onclose=()=>resolve(null);$('#dialog').showModal();if(input)setTimeout(()=>$('#dialogInput').focus(),0)})}
async function remove(x){if(!await modal({title:t.confirmTitle,text:t.confirm+' “'+x.name+'”?',ok:t.remove}))return;let p=(path==='/'?'':path)+'/'+x.name,r=await fetch('/api/delete',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'path='+encodeURIComponent(p)});if(!r.ok)toast((await r.json()).error,true);else load()}
$('#mkdir').onclick=async()=>{let n=await modal({title:t.nameTitle,text:t.name,input:true,ok:t.create});if(!n)return;let r=await fetch('/api/mkdir',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'path='+encodeURIComponent(path)+'&name='+encodeURIComponent(n)});if(!r.ok)toast((await r.json()).error,true);else load()};
$('#pick').onclick=()=>$('#files').click();$('#files').onchange=()=>queue([...$('#files').files]);let drop=$('#drop');drop.onclick=()=>$('#files').click();drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#files').click()}};for(const ev of ['dragenter','dragover'])drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('over')});for(const ev of ['dragleave','drop'])drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('over')});drop.addEventListener('drop',e=>queue([...e.dataTransfer.files]));
async function queue(files){let valid=files.filter(x=>x.name.toLowerCase().endsWith('.epub'));if(!valid.length)return;$('#jobsWrap').hidden=false;for(const f of valid){let div=document.createElement('div');div.className='card job';div.innerHTML='<span class="ico">'+icons.file+'</span><span class="job-name">'+esc(f.name)+'</span><progress max="100" value="0"></progress><span class="job-state">0%</span>';$('#jobs').append(div);try{await upload(f,div);toast(t.success)}catch(e){div.querySelector('.job-state').textContent=t.failed;toast(e.message||t.network,true)}}load()}
function upload(f,row){return new Promise((ok,no)=>{let x=new XMLHttpRequest(),form=new FormData();form.append('file',f,f.name);x.open('POST','/api/upload');x.setRequestHeader('X-Dest-Path',path);x.setRequestHeader('X-File-Size',f.size);x.upload.onprogress=e=>{if(e.lengthComputable){let p=Math.round(e.loaded*100/e.total);row.querySelector('progress').value=p;row.querySelector('.job-state').textContent=p+'%'}};x.onload=()=>x.status<300?ok():no(Error(x.responseText));x.onerror=()=>no(Error(t.network));x.send(form)})}load();
</script></body></html>)PORTAL";
#endif
